/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include "../../fhe_types_v2.h"

#line 1 "cgo-generated-wrapper"

#line 3 "bootstrap.go"

#include "../../fhe_types_v2.h"

#line 1 "cgo-generated-wrapper"

#line 3 "c_struct_import_export.go"

#include "../../fhe_types_v2.h"

#line 1 "cgo-generated-wrapper"

#line 3 "conversion.go"

#include "../../fhe_types_v2.h"

#line 1 "cgo-generated-wrapper"

#line 3 "multiparty.go"

#include "../../fhe_types_v2.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* GetErrorMessage();
extern GoUint64 CreateBfvParameter(GoUint64 N, GoUint64 T);
extern GoUint64 CreateCustomBfvParameter();
extern GoUint64 CreateCustomCkksParameter();
extern GoUint64 CreateCkksParameter(GoUint64 N);
extern GoUint64 CreateBfvParameterV2(GoUint64 T);
extern GoUint64 CreateCkksParameterV2();
extern GoUint64 SetBfvParameter(GoUint64 N, GoUint64 T, uint64_t* Q, GoInt q_len, uint64_t* P, GoInt p_len);
extern GoUint64 SetCkksParameter(GoUint64 N, uint64_t* Q, GoInt q_len, uint64_t* P, GoInt p_len);
extern GoUint64 CopyBfvParameter(GoUint64 parameter_handle);
extern GoUint64 CopyCkksParameter(GoUint64 parameter_handle);
extern void PrintBfvParameter(GoUint64 parameter_handle);
extern void PrintCkksParameter(GoUint64 parameter_handle);
extern GoUint64 GetBfvQ(GoUint64 parameter_handle, GoInt index);
extern GoInt GetBfvQCount(GoUint64 parameter_handle);
extern GoUint64 GetBfvP(GoUint64 parameter_handle, GoInt index);
extern GoInt GetBfvPCount(GoUint64 parameter_handle);
extern GoInt GetBfvN(GoUint64 parameter_handle);
extern GoUint64 GetBfvT(GoUint64 parameter_handle);
extern GoUint64 GetBfvContextT(GoUint64 context_handle);
extern GoInt GetCkksN(GoUint64 parameter_handle);
extern GoInt GetBfvMaxLevel(GoUint64 parameter_handle);
extern GoInt GetCkksMaxLevel(GoUint64 parameter_handle);
extern GoUint64 GetCkksP(GoUint64 parameter_handle, GoInt index);
extern GoInt GetCkksPCount(GoUint64 parameter_handle);
extern GoUint64 GetCkksQ(GoUint64 parameter_handle, GoInt index);
extern GoFloat64 GetDefaultScale(GoUint64 parameter_handle);
extern GoUint64 CreateEmptyBfvContext(GoUint64 parameter_handle);
extern GoUint64 CreateRandomBfvContext(GoUint64 parameter_handle, GoInt level);
extern GoUint64 CreateEmptyCkksContext(GoUint64 parameter_handle, GoUint8 support_big_complex);
extern GoUint64 CreateRandomCkksContext(GoUint64 parameter_handle, GoInt level, GoUint8 support_big_complex);
extern GoUint64 CreateRandomCkksContextWithSeed(GoUint64 parameter_handle, GoUint8* seed, GoUint8 support_big_complex);
extern GoUint64 CreateCkksExtraLevelContext(GoUint64 context_handle);
extern GoUint64 MakePublicBfvContext(GoUint64 context_handle, GoUint8 include_pk, GoUint8 include_rlk, GoUint8 include_gk);
extern GoUint64 MakePublicCkksContext(GoUint64 context_handle, GoUint8 include_pk, GoUint8 include_rlk, GoUint8 include_gk);
extern void GenerateBfvContextPublicKeys(GoUint64 context_handle, GoInt level);
extern GoUint64 ShallowCopyBfvContext(GoUint64 context_handle);
extern GoUint64 ShallowCopyCkksContext(GoUint64 context_handle);
extern void GenBfvContextRotationKeys(GoUint64 context_handle, GoInt level);
extern void GenBfvContextRotationKeysForRotations(GoUint64 context_handle, GoInt32* rots, GoInt rots_length, GoUint8 include_swap_rows, GoInt level);
extern void GenCkksContextRotationKeys(GoUint64 context_handle, GoInt level);
extern void GenCkksContextRotationKeysForRotations(GoUint64 context_handle, GoInt32* rots, GoInt rots_length, GoUint8 include_swap_rows, GoInt level);
extern GoUint64 ExtractBfvSecretKey(GoUint64 context_handle);
extern GoUint64 ExtractCkksSecretKey(GoUint64 context_handle);
extern GoUint64 ExtractBfvPublicKey(GoUint64 context_handle);
extern GoUint64 ExtractCkksPublicKey(GoUint64 context_handle);
extern GoUint64 ExtractBfvRelinKey(GoUint64 context_handle);
extern GoUint64 ExtractCkksRelinKey(GoUint64 context_handle);
extern GoUint64 ExtractKeySwitchKeyFromRelinKey(GoUint64 relin_key_handle);
extern GoInt ExtractKeySwitchKeyFromGaloisKey(GoUint64 relin_key_handle, GoUint64 k, uint64_t* key_switch_key_handle);
extern GoUint64 ExtractBfvGaloisKey(GoUint64 context_handle);
extern GoUint64 ExtractCkksGaloisKey(GoUint64 context_handle);
extern void SetBfvContextSecretKey(GoUint64 context_handle, GoUint64 secret_key_handle);
extern void SetCkksContextSecretKey(GoUint64 context_handle, GoUint64 secret_key_handle);
extern void SetBfvContextPublicKey(GoUint64 context_handle, GoUint64 public_key_handle);
extern void SetCkksContextPublicKey(GoUint64 context_handle, GoUint64 public_key_handle);
extern void SetBfvContextRelinKey(GoUint64 context_handle, GoUint64 relin_key_handle);
extern void SetCkksContextRelinKey(GoUint64 context_handle, GoUint64 relin_key_handle);
extern void SetBfvContextGaloisKey(GoUint64 context_handle, GoUint64 galois_key_handle);
extern void SetCkksContextGaloisKey(GoUint64 context_handle, GoUint64 galois_key_handle);
extern GoUint64 GetBfvParameter(GoUint64 context_handle);
extern GoUint64 GetCkksParameter(GoUint64 context_handle);
extern GoUint64 NewBfvCiphertext(GoUint64 context_handle, GoInt degree, GoInt level);
extern GoUint64 CopyBfvCiphertext(GoUint64 x_ciphertext_handle);
extern GoUint64 CopyBfvCiphertextTo(GoUint64 x_ciphertext_handle, GoUint64 y_ciphertext_handle);
extern GoUint64 CopyCkksCiphertext(GoUint64 x_ciphertext_handle);
extern GoUint64 CopyCkksCiphertextTo(GoUint64 x_ciphertext_handle, GoUint64 y_ciphertext_handle);
extern GoUint64 CopyCkksCiphertext3To(GoUint64 x_ciphertext_handle, GoUint64 y_ciphertext_handle);
extern void ReleaseHandle(GoUint64 handle);
extern GoUint64 SerializeBfvContext(GoUint64 context_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeBfvContext(GoUint8* raw_data, GoUint64 length);
extern GoUint64 SerializeBfvContextAdvanced(GoUint64 context_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeBfvContextAdvanced(GoUint8* raw_data, uint64_t length);
extern void BfvContextDecompress(GoUint64 context_handle);
extern GoUint64 SerializeCkksContext(GoUint64 context_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 SerializeCkksSecretKey(GoUint64 context_handle, GoInt data_bit_length, GoUint8** raw_data, uint64_t* length);
extern GoUint64 SerializeCkksPublicKey(GoUint64 context_handle, GoInt data_bit_length, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeCkksContext(GoUint8* raw_data, uint64_t length);
extern GoUint64 DeserializeCkksSecretKey(GoUint8* raw_data, uint64_t length, GoInt data_bit_length);
extern GoUint64 DeserializeCkksPublicKey(GoUint8* raw_data, uint64_t length, GoInt data_bit_length);
extern GoUint64 SerializeCkksContextAdvanced(GoUint64 context_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeCkksContextAdvanced(GoUint8* raw_data, uint64_t length);
extern void CkksContextDecompress(GoUint64 context_handle);
extern GoUint64 SerializeBfvCiphertext(GoUint64 ciphertext_handle, GoUint64 param_handle, GoUint8** raw_data, uint64_t* length, GoInt n_drop_bit_0, GoInt n_drop_bit_1);
extern GoUint64 SerializeBfvCompressedCiphertext(GoUint64 ciphertext_handle, GoUint64 param_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 SerializeCkksCiphertext(GoUint64 ciphertext_handle, GoUint64 param_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 SerializeCkksCompressedCiphertext(GoUint64 ciphertext_handle, GoUint64 param_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeBfvCiphertext(GoUint8* raw_data, uint64_t length);
extern GoUint64 DeserializeBfvCompressedCiphertext(GoUint8* raw_data, uint64_t length);
extern GoUint64 DeserializeCkksCiphertext(GoUint8* raw_data, uint64_t length);
extern GoUint64 DeserializeCkksCompressedCiphertext(GoUint8* raw_data, uint64_t length);
extern GoInt GetBfvCiphertextLevel(GoUint64 x_ciphertext_handle);
extern GoUint64 GetBfvCiphertextCoeff(GoUint64 x_ciphertext_handle, GoInt poly_idx, GoInt rns_idx, GoInt coeff_idx);
extern GoInt GetBfvCiphertext3Level(GoUint64 x_ciphertext_3_handle);
extern GoInt GetBfvPlaintextLevel(GoUint64 x_plaintext_handle);
extern GoInt GetBfvPlaintextRingtLevel(GoUint64 x_plaintext_ringt_handle);
extern GoInt GetBfvPlaintextMulLevel(GoUint64 x_plaintext_mul_handle);
extern GoInt GetCkksCiphertextLevel(GoUint64 x_ciphertext_handle);
extern GoInt GetCkksCiphertext3Level(GoUint64 x_ciphertext_3_handle);
extern GoInt GetCkksPlaintextLevel(GoUint64 x_plaintext_handle);
extern GoInt GetCkksPlaintextRingtLevel(GoUint64 x_plaintext_ringt_handle);
extern GoInt GetCkksPlaintextMulLevel(GoUint64 x_plaintext_mul_handle);
extern GoInt GetKeySwitchKeyLevel(GoUint64 key_switch_key_handle);
extern GoFloat64 GetCkksCiphertextScale(GoUint64 x_ciphertext_handle);
extern GoFloat64 SetCkksCiphertextScale(GoUint64 x_ciphertext_handle, GoFloat64 scale_in);
extern GoUint64 GetCkksPlaintextCoeff(GoUint64 x_plaintext_handle, GoInt rns_idx, GoInt coeff_idx);
extern void SetCkksPlaintextCoeff(GoUint64 x_plaintext_handle, GoInt rns_idx, GoInt coeff_idx, GoUint64 coeff);
extern GoInt BfvEncode(GoUint64 context_handle, uint64_t* message_array, GoInt mg_len, GoInt level, uint64_t* plaintext_handle);
extern GoInt BfvEncodeRingt(GoUint64 context_handle, uint64_t* message_array, GoInt mg_len, uint64_t* plaintext_handle);
extern GoUint64 BfvEncodeMul(GoUint64 context_handle, uint64_t* message_array, GoInt mg_len, GoInt level);
extern GoUint64 BfvEncodeCoeffs(GoUint64 context_handle, uint64_t* message_array, GoInt mg_len, GoInt level);
extern GoUint64 BfvEncodeCoeffsRingt(GoUint64 context_handle, uint64_t* message_array, GoInt mg_len);
extern GoUint64 BfvEncodeCoeffsMul(GoUint64 context_handle, uint64_t* message_array, GoInt mg_len, GoInt level);
extern GoUint64 CkksEncode(GoUint64 context_handle, double* message_array, GoInt mg_len, GoInt level, GoFloat64 scale);
extern GoUint64 CkksEncodeComplex(GoUint64 context_handle, double* message_array, GoInt mg_len, GoInt level, GoFloat64 scale);
extern GoUint64 CkksEncodeRingt(GoUint64 context_handle, double* message_array, GoInt mg_len, GoFloat64 scale);
extern GoUint64 CkksEncodeMul(GoUint64 context_handle, double* message_array, GoInt mg_len, GoInt level, GoFloat64 scale);
extern GoUint64 CkksEncodeCoeffs(GoUint64 context_handle, double* message_array, GoInt mg_len, GoInt level, GoFloat64 scale);
extern GoUint64 CkksEncodeCoeffsRingt(GoUint64 context_handle, double* message_array, GoInt mg_len, GoFloat64 scale);
extern GoUint64 CkksEncodeCoeffsMul(GoUint64 context_handle, double* message_array, GoInt mg_len, GoInt level, GoFloat64 scale);
extern GoUint64 BfvDecode(GoUint64 context_handle, GoUint64 plaintext_handle, uint64_t** raw_data, uint64_t* length);
extern GoUint64 BfvDecodeRingt(GoUint64 context_handle, GoUint64 plaintext_handle, uint64_t** raw_data, uint64_t* length);
extern GoUint64 BfvDecodeCoeffs(GoUint64 context_handle, GoUint64 plaintext_handle, uint64_t** raw_data, uint64_t* length);
extern GoUint64 CkksDecode(GoUint64 context_handle, GoUint64 plaintext_handle, double** raw_data, uint64_t* length);
extern GoUint64 CkksDecodeCoeffs(GoUint64 context_handle, GoUint64 plaintext_handle, double** raw_data, uint64_t* length);
extern GoUint64 CkksRecodeBigComplex(GoUint64 context_handle, GoUint64 plaintext_handle, GoInt level, GoFloat64 scale);
extern GoUint64 BfvEncryptAsymmetric(GoUint64 context_handle, GoUint64 plaintext_handle);
extern GoUint64 CkksEncryptAsymmetric(GoUint64 context_handle, GoUint64 plaintext_handle);
extern GoInt BfvEncryptSymmetric(GoUint64 context_handle, GoUint64 plaintext_handle, uint64_t* ciphertext_handle);
extern GoInt BfvEncryptSymmetricCompressed(GoUint64 context_handle, GoUint64 plaintext_handle, uint64_t* ciphertext_handle);
extern GoUint64 BfvCompressedCiphertextToCiphertext(GoUint64 context_handle, GoUint64 ciphertext_handle);
extern GoUint64 CkksEncryptSymmetric(GoUint64 context_handle, GoUint64 plaintext_handle);
extern GoUint64 CkksEncryptSymmetricCompressed(GoUint64 context_handle, GoUint64 plaintext_handle);
extern GoUint64 CkksCompressedCiphertextToCiphertext(GoUint64 context_handle, GoUint64 ciphertext_handle);
extern GoInt BfvDecrypt(GoUint64 context_handle, GoUint64 ciphertext_handle, uint64_t* plaintext_handle);
extern GoUint64 CkksDecrypt(GoUint64 context_handle, GoUint64 ciphertext_handle, uint64_t* plaintext_handle);
extern GoUint64 BfvPlaintextToPlaintextRingt(GoUint64 context_handle, GoUint64 plaintext_handle);
extern GoUint64 BfvPlaintextRingtToPlaintextMul(GoUint64 context_handle, GoUint64 plaintext_ringt_handle, GoInt level);
extern GoUint64 BfvPlaintextRingtToPlaintext(GoUint64 context_handle, GoUint64 plaintext_ringt_handle, GoInt level);
extern GoUint64 CkksPlaintextRingtToPlaintextMul(GoUint64 context_handle, GoUint64 plaintext_ringt_handle, GoInt level);
extern GoUint64 CkksPlaintextRingtToPlaintext(GoUint64 context_handle, GoUint64 plaintext_ringt_handle, GoInt level);
extern GoInt BfvAdd(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_ciphertext_handle, uint64_t* y_ciphertext_handle);
extern GoUint64 BfvSub(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_ciphertext_handle);
extern GoUint64 BfvSubPlain(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 BfvSubPlainRingt(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 BfvNegate(GoUint64 context_handle, GoUint64 x0_ciphertext_handle);
extern void AddInplace(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_ciphertext_handle);
extern GoUint64 BfvAddPlain(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 BfvAddPlainRingt(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern void AddPlainInplace(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 CkksAdd(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_ciphertext_handle);
extern GoUint64 CkksAddPlain(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 CkksSub(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_ciphertext_handle);
extern GoUint64 CkksSubPlain(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 CkksAddPlainRingt(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 CkksSubPlainRingt(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 CkksNegate(GoUint64 context_handle, GoUint64 x0_ciphertext_handle);
extern GoUint64 BfvMult(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_ciphertext_handle);
extern GoUint64 CkksMult(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_ciphertext_handle);
extern GoUint64 BfvMultPlain(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 BfvMultPlainRingt(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_ringt_handle);
extern GoUint64 BfvMultPlainMul(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_mul_handle);
extern GoUint64 BfvMultScalar(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoInt64 x1_value);
extern GoUint64 CkksMultPlain(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 CkksMultPlainMul(GoUint64 context_handle, GoUint64 x0_ciphertext_handle, GoUint64 x1_plaintext_handle);
extern GoUint64 BfvRelinearize(GoUint64 context_handle, GoUint64 x_ciphertext3_handle);
extern GoUint64 CkksRelinearize(GoUint64 context_handle, GoUint64 x_ciphertext3_handle);
extern GoUint64 BfvRescale(GoUint64 context_handle, GoUint64 x_ciphertext_handle);
extern GoUint64 CkksDropLevel(GoUint64 context_handle, GoUint64 x_ciphertext_handle, GoInt32 levels);
extern GoUint64 CkksRescale(GoUint64 context_handle, GoUint64 x_ciphertext_handle, GoFloat64 min_scale);
extern GoInt BfvRotateColumns(GoUint64 context_handle, GoUint64 x_ciphertext_handle, GoInt32* steps, GoInt length, uint64_t* y_ciphertext_handles);
extern GoInt BfvAdvancedRotateColumns(GoUint64 context_handle, GoUint64 x_ciphertext_handle, GoInt32* steps, GoInt length, uint64_t* y_ciphertext_handles);
extern GoUint64 BfvRotateRows(GoUint64 context_handle, GoUint64 x_ciphertext_handle);
extern GoInt CkksRotate(GoUint64 context_handle, GoUint64 x_ciphertext_handle, GoInt32* steps, GoInt length, uint64_t* y_ciphertext_handles);
extern GoUint64 CkksConjugate(GoUint64 context_handle, GoUint64 x_ciphertext_handle);
extern GoInt CkksAdvancedRotate(GoUint64 context_handle, GoUint64 x_ciphertext_handle, GoInt32* steps, GoInt length, uint64_t* y_ciphertext_handles);
extern GoUint64 NewCkksCiphertext(GoUint64 context_handle, GoInt degree, GoInt level, GoFloat64 scale);
extern void PrintCkksCiphertext(GoUint64 x_ciphertext_handle);
extern void PrintBfvCiphertext(GoUint64 x_ciphertext_handle);
extern void PrintBfvPlaintext(GoUint64 x_plaintext_handle);
extern void PrintMemUsage();
extern GoUint64 CkksPolyEvalStepFunction(GoUint64 context_handle, GoUint64 x_ciphertext_handle, GoFloat64 a, GoFloat64 b, GoInt degree, GoFloat64 threshold);
extern GoUint64 PolyEvalFunction(void* f, GoUint64 context_handle, GoUint64 x_ciphertext_handle, GoFloat64 left, GoFloat64 right, GoInt degree);
extern GoUint64 PolyEvalReluFunction(GoUint64 context_handle, GoUint64 x_ciphertext_handle, GoFloat64 left, GoFloat64 right, GoInt degree);
extern GoUint64 CreateCkksBtpParameter();
extern GoUint64 CreateCkksToyBtpParameter();
extern GoUint64 GetCkksParameterFromBtpParameter(GoUint64 parameter_handle);
extern GoUint64 CreateRandomCkksBtpContext(GoUint64 parameter_handle);
extern void GenCkksBtpContextRotationKeys(GoUint64 context_handle);
extern void GenCkksBtpContextRotationKeysForRotations(GoUint64 context_handle, GoInt32* rots, GoInt rots_length, GoUint8 include_swap_rows);
extern GoUint64 ShallowCopyCkksBtpContext(GoUint64 context_handle);
extern GoUint64 MakePublicCkksBtpContext(GoUint64 context_handle);
extern GoUint64 GetCkksBtpParameter(GoUint64 context_handle);
extern GoUint64 GetCkksSchemeParameter(GoUint64 context_handle);
extern GoUint64 CkksBootstrap(GoUint64 context_handle, GoUint64 x_ciphertext_handle);
extern GoUint64 ExtractCkksBtpSwkDtS(GoUint64 context_handle);
extern GoUint64 ExtractCkksBtpSwkStD(GoUint64 context_handle);
extern GoUint64 CreateEmptyCkksBtpContext(GoUint64 parameter_handle);
extern void SetCkksBtpContextRelinKey(GoUint64 context_handle, GoUint64 relin_key_handle);
extern void SetCkksBtpContextGaloisKey(GoUint64 context_handle, GoUint64 galois_key_handle);
extern void SetCkksBtpContextSwitchkeyDts(GoUint64 context_handle, GoUint64 switch_key_handle);
extern void SetCkksBtpContextSwitchkeyStd(GoUint64 context_handle, GoUint64 switch_key_handle);
extern void CreateCkksBtpContextBootstrapper(GoUint64 context_handle);
extern GoUint64 SerializeCkksBtpContextAdvanced(GoUint64 context_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeCkksBtpContextAdvanced(GoUint8* raw_data, GoUint64 length);
extern GoUint64 ImportBfvCiphertext(GoUint64 parameter_handle, CCiphertext* c_ciphertext);
extern GoUint64 ImportCkksCiphertext(GoUint64 parameter_handle, CCiphertext* c_ciphertext);
extern void ExportBfvPlaintextRingt(GoUint64 plaintext_ringt_handle, CPlaintext* c_plaintext);
extern void ExportCkksPlaintextRingt(GoUint64 plaintext_ringt_handle, CPlaintext* c_plaintext);
extern void ExportBfvPlaintextMul(GoUint64 plaintext_mul_handle, CPlaintext* c_plaintext);
extern void ExportCkksPlaintextMul(GoUint64 plaintext_mul_handle, CPlaintext* c_plaintext);
extern void ExportBfvPlaintext(GoUint64 plaintext_handle, CPlaintext* c_plaintext);
extern void ExportCkksPlaintext(GoUint64 plaintext_handle, CPlaintext* c_plaintext);
extern void ExportBfvCiphertext(GoUint64 ciphertext_handle, CCiphertext* c_ciphertext);
extern void ExportCkksCiphertext(GoUint64 ciphertext_handle, CCiphertext* c_ciphertext);
extern void ExportRelinKey(GoUint64 relin_key_handle, GoInt level, CRelinKey* c_relin_key);
extern void ExportGaloisKey(GoUint64 galois_key_handle, GoInt level, CGaloisKey* c_galois_key);
extern void ExportSwitchingKey(GoUint64 switch_key_handle, GoInt level, GoInt sp_level, CKeySwitchKey* c_switch_key);
extern void BfvComponentNttInplace(GoUint64 parameter_handle, long unsigned int* coeff, GoInt lvl_idx);
extern void BfvComponentInvNttInplace(GoUint64 parameter_handle, long unsigned int* coeff, GoInt lvl_idx);
extern void CkksComponentNttInplace(GoUint64 parameter_handle, long unsigned int* coeff, GoInt lvl_idx);
extern void CkksComponentInvNttInplace(GoUint64 parameter_handle, long unsigned int* coeff, GoInt lvl_idx);
extern void BfvComponentMulByPow2Inplace(GoUint64 parameter_handle, long unsigned int* coeff, GoInt lvl_idx, GoInt pow2);
extern void CkksComponentMulByPow2Inplace(GoUint64 parameter_handle, long unsigned int* coeff, GoInt lvl_idx, GoInt pow2);
extern void BfvPlaintextMulInvMFormAndMulByPow2(GoUint64 parameter_handle, GoUint64 plaintext_mul_handle, GoInt pow2);
extern void CkksPlaintextMulInvMFormAndMulByPow2(GoUint64 parameter_handle, GoUint64 plaintext_mul_handle, GoInt pow2);
extern void BfvRlkInvMForm(GoUint64 parameter_handle, GoUint64 relin_key_handle);
extern void BfvRlkInvMFormAndMulByPow2(GoUint64 parameter_handle, GoUint64 relin_key_handle, GoInt pow2);
extern void BfvGlkInvMForm(GoUint64 parameter_handle, GoUint64 galois_key_handle);
extern void BfvGlkInvMFormAndMulByPow2(GoUint64 parameter_handle, GoUint64 galois_key_handle, GoInt pow2);
extern void CkksRlkInvMForm(GoUint64 parameter_handle, GoUint64 relin_key_handle);
extern void CkksRlkInvMFormAndMulByPow2(GoUint64 parameter_handle, GoUint64 relin_key_handle, GoInt pow2);
extern void CkksGlkInvMForm(GoUint64 parameter_handle, GoUint64 galois_key_handle);
extern void CkksGlkInvMFormAndMulByPow2(GoUint64 parameter_handle, GoUint64 galois_key_handle, GoInt pow2);
extern void SetBfvRlkNMFormBits(GoUint64 parameter_handle, GoUint64 relin_key_handle, GoInt n_mform_bits);
extern void SetCkksRlkNMFormBits(GoUint64 parameter_handle, GoUint64 relin_key_handle, GoInt n_mform_bits);
extern void SetBfvGlkNMFormBits(GoUint64 parameter_handle, GoUint64 galois_key_handle, GoInt n_mform_bits);
extern void SetBfvGlkNMFormBitsForGaloisElement(GoUint64 parameter_handle, GoUint64 galois_key_handle, GoUint64 galois_element, GoInt n_mform_bits);
extern void SetCkksSwkNMFormBits(GoUint64 parameter_handle, GoUint64 switching_key_handle, GoInt n_mform_bits);
extern void SetCkksGlkNMFormBits(GoUint64 parameter_handle, GoUint64 galois_key_handle, GoInt n_mform_bits);
extern void SetCkksGlkNMFormBitsForGaloisElement(GoUint64 parameter_handle, GoUint64 galois_key_handle, GoUint64 galois_element, GoInt n_mform_bits);
extern GoUint64 CreateRandomDBfvContext(GoUint64 context_handle, GoUint8* crs_seed, GoFloat64 sigma_smudging);
extern GoUint64 GetDBfvBfvContext(GoUint64 context_handle);
extern GoUint64 CreateCKGContext(GoUint64 context_handle);
extern GoUint64 GenDBfvPublicKeyShare(GoUint64 context_handle);
extern GoUint64 AggregateDBfvPublicKeyShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern void SetDBfvPublicKey(GoUint64 context_handle, GoUint64 share_handle);
extern GoUint64 SerializeDBfvPublicKeyShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvPublicKeyShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateE2SContext(GoUint64 context_handle);
extern GoUint64 GenDBfvE2SPublicAndSecretShare(GoUint64 context_handle, GoUint64 ciphertext_handle, uint64_t* secret_share_handle);
extern GoUint64 AggregateDBfvE2SCKSShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 GetDBfvE2SSecretShare(GoUint64 context_handle, GoUint64 ciphertext_handle, GoUint64 public_share_handle, GoUint64 secret_share_handle);
extern GoUint64 AggregateDBfvAdditiveShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 SetDBfvE2SPlaintextRingT(GoUint64 context_handle, GoUint64 secret_share_handle);
extern GoUint64 SerializeDBfvCKSShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvE2SCKSShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 SerializeDBfvAdditiveShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvAdditiveShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateS2EContext(GoUint64 context_handle);
extern GoUint64 GenDBfvS2EPublicShare(GoUint64 context_handle, GoUint64 secret_share_handle);
extern GoUint64 AggregateDBfvS2ECKSShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 SetDBfvS2ECiphertext(GoUint64 context_handle, GoUint64 public_share_handle);
extern GoUint64 DeserializeDBfvS2ECKSShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateRKGContext(GoUint64 context_handle);
extern GoUint64 GenDBfvRelinKeyShareRoundOne(GoUint64 context_handle, uint64_t* eph_sk_handle);
extern GoUint64 AggregateDBfvRelinKeyShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 GenDBfvRelinKeyShareRoundTwo(GoUint64 context_handle, GoUint64 eph_sk_handle, GoUint64 share1_handle);
extern void SetDBfvRelinKey(GoUint64 context_handle, GoUint64 share1_handle, GoUint64 share2_handle);
extern GoUint64 SerializeDBfvRelinKeyShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvRelinKeyShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateRTGContext(GoUint64 context_handle);
extern GoInt GenDBfvGaloisKeyShare(GoUint64 context_handle, GoInt32* rots, GoInt rots_length, GoUint8 include_swap_rows, uint64_t* share_handles);
extern GoInt AggregateDBfvGaloisKeyShare(GoUint64 context_handle, uint64_t* x0_share_handles, uint64_t* x1_share_handles, GoInt length, uint64_t* y_share_handles);
extern void SetDBfvRotationKey(GoUint64 context_handle, GoInt32* rots, GoInt rots_length, GoUint8 include_swap_rows, uint64_t* share_handles);
extern GoUint64 SerializeDBfvGaloisKeyShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvGaloisKeyShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateRefreshContext(GoUint64 context_handle);
extern GoUint64 GenDBfvRefreshShare(GoUint64 context_handle, GoUint64 ciphertext_handle);
extern GoUint64 AggregateDBfvRefreshShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 DBfvRefreshFinalize(GoUint64 context_handle, GoUint64 ciphertext_handle, GoUint64 share_handle);
extern GoUint64 SerializeDBfvRefreshShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvRefreshShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateRefreshAndPermuteContext(GoUint64 context_handle);
extern GoUint64 GenDBfvRefreshAndPermuteShare(GoUint64 context_handle, GoUint64 ciphertext_handle, uint64_t* permute);
extern GoUint64 AggregateDBfvRefreshAndPermuteShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 DBfvRefreshAndPermuteTransform(GoUint64 context_handle, GoUint64 ciphertext_handle, uint64_t* permute, GoUint64 share_handle);
extern GoUint64 SerializeDBfvRefreshAndPermuteShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvvRefreshAndPermuteShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);

#ifdef __cplusplus
}
#endif
