package rlwe

import (
	"bufio"
	"bytes"
	"fmt"
	"io"

	"github.com/tuneinsight/lattigo/v4/utils/buffer"
	"github.com/tuneinsight/lattigo/v4/utils/structs"
)

// EvaluationKeySet is an interface implementing methods
// to load the RelinearizationKey and GaloisKeys in the Evaluator.
// Implementations of this interface must be safe for concurrent use.
type EvaluationKeySet interface {

	// GetGaloisKey retrieves the Galois key for the automorphism X^{i} -> X^{i*galEl}.
	GetGaloisKey(galEl uint64) (evk *GaloisKey, err error)

	// GetGaloisKeysList returns the list of all the Galois elements
	// for which a Galois key exists in the object.
	GetGaloisKeysList() (galEls []uint64)

	// GetRelinearizationKey retrieves the RelinearizationKey.
	GetRelinearizationKey() (evk *RelinearizationKey, err error)
}

// MemEvaluationKeySet is a basic in-memory implementation of the EvaluationKeySet interface.
type MemEvaluationKeySet struct {
	Rlk *RelinearizationKey
	Gks structs.Map[uint64, GaloisKey]
}

// NewMemEvaluationKeySet returns a new EvaluationKeySet with the provided RelinearizationKey and GaloisKeys.
func NewMemEvaluationKeySet(relinKey *RelinearizationKey, galoisKeys ...*GaloisKey) (eks *MemEvaluationKeySet) {
	eks = &MemEvaluationKeySet{Gks: map[uint64]*GaloisKey{}}
	eks.Rlk = relinKey
	for _, k := range galoisKeys {
		eks.Gks[k.GaloisElement] = k
	}
	return eks
}

// GetGaloisKey retrieves the Galois key for the automorphism X^{i} -> X^{i*galEl}.
func (evk *MemEvaluationKeySet) GetGaloisKey(galEl uint64) (gk *GaloisKey, err error) {
	var ok bool
	if gk, ok = evk.Gks[galEl]; !ok {
		return nil, fmt.Errorf("GaloiKey[%d] is nil", galEl)
	}

	return
}

// GetGaloisKeysList returns the list of all the Galois elements
// for which a Galois key exists in the object.
func (evk *MemEvaluationKeySet) GetGaloisKeysList() (galEls []uint64) {

	if evk == nil || evk.Gks == nil {
		return []uint64{}
	}

	galEls = make([]uint64, len(evk.Gks))

	var i int
	for galEl := range evk.Gks {
		galEls[i] = galEl
		i++
	}

	return
}

// GetRelinearizationKey retrieves the RelinearizationKey.
func (evk *MemEvaluationKeySet) GetRelinearizationKey() (rk *RelinearizationKey, err error) {
	if evk.Rlk != nil {
		return evk.Rlk, nil
	}

	return nil, fmt.Errorf("RelinearizationKey is nil")
}

// MarshalBinary encodes the object into a binary form on a newly allocated slice of bytes.
func (evk *MemEvaluationKeySet) MarshalBinary() (p []byte, err error) {
	buf := bytes.NewBuffer([]byte{})
	_, err = evk.WriteTo(buf)
	return buf.Bytes(), err
}

// UnmarshalBinary decodes a slice of bytes generated by
// MarshalBinary or WriteTo on the object.
func (evk *MemEvaluationKeySet) UnmarshalBinary(p []byte) (err error) {
	_, err = evk.ReadFrom(bytes.NewBuffer(p))
	return
}

// WriteTo writes the object on an io.Writer.
// To ensure optimal efficiency and minimal allocations, the user is encouraged
// to provide a struct implementing the interface buffer.Writer, which defines
// a subset of the method of the bufio.Writer.
// If w is not compliant to the buffer.Writer interface, it will be wrapped in
// a new bufio.Writer.
// For additional information, see lattigo/utils/buffer/writer.go.
func (evk *MemEvaluationKeySet) WriteTo(w io.Writer) (int64, error) {
	switch w := w.(type) {
	case buffer.Writer:

		var inc int
		var n, inc64 int64
		var err error

		if evk.Rlk != nil {
			if inc, err = buffer.WriteUint8(w, 1); err != nil {
				return int64(inc), err
			}

			n += int64(inc)

			if inc64, err = evk.Rlk.WriteTo(w); err != nil {
				return n + inc64, err
			}

			n += inc64

		} else {
			if inc, err = buffer.WriteUint8(w, 0); err != nil {
				return int64(inc), err
			}
			n += int64(inc)
		}

		if evk.Gks != nil {
			if inc, err = buffer.WriteUint8(w, 1); err != nil {
				return int64(inc), err
			}

			n += int64(inc)

			if inc64, err = evk.Gks.WriteTo(w); err != nil {
				return n + inc64, err
			}

			n += inc64

		} else {
			if inc, err = buffer.WriteUint8(w, 0); err != nil {
				return int64(inc), err
			}
			n += int64(inc)
		}

		return n, w.Flush()

	default:
		return evk.WriteTo(bufio.NewWriter(w))
	}
}

// ReadFrom reads on the object from an io.Writer.
// To ensure optimal efficiency and minimal allocations, the user is encouraged
// to provide a struct implementing the interface buffer.Reader, which defines
// a subset of the method of the bufio.Reader.
// If r is not compliant to the buffer.Reader interface, it will be wrapped in
// a new bufio.Reader.
// For additional information, see lattigo/utils/buffer/reader.go.
func (evk *MemEvaluationKeySet) ReadFrom(r io.Reader) (n int64, err error) {
	switch r := r.(type) {
	case buffer.Reader:
		var inc int
		var n, inc64 int64
		var err error

		var hasKey uint8

		if inc, err = buffer.ReadUint8(r, &hasKey); err != nil {
			return int64(inc), err
		}

		n += int64(inc)

		if hasKey == 1 {

			if evk.Rlk == nil {
				evk.Rlk = new(RelinearizationKey)
			}

			if inc64, err = evk.Rlk.ReadFrom(r); err != nil {
				return n + inc64, err
			}

			n += inc64
		}

		if inc, err = buffer.ReadUint8(r, &hasKey); err != nil {
			return int64(inc), err
		}

		n += int64(inc)

		if hasKey == 1 {

			if evk.Gks == nil {
				evk.Gks = structs.Map[uint64, GaloisKey]{}
			}

			if inc64, err = evk.Gks.ReadFrom(r); err != nil {
				return n + inc64, err
			}

			n += inc64
		}

		return n, nil

	default:
		return evk.ReadFrom(bufio.NewReader(r))
	}
}

func (evk *MemEvaluationKeySet) BinarySize() (size int) {

	size++
	if evk.Rlk != nil {
		size += evk.Rlk.BinarySize()
	}

	size++
	if evk.Gks != nil {
		size += evk.Gks.BinarySize()
	}

	return
}

// Encode encodes the object into a binary form on a preallocated slice of bytes
// and returns the number of bytes written.
func (evk *MemEvaluationKeySet) Encode(p []byte) (n int, err error) {
	var inc int
	if evk.Rlk != nil {
		p[n] = 1
		n++

		if inc, err = evk.Rlk.Encode(p[n:]); err != nil {
			return n + inc, err
		}

		n += inc

	} else {
		n++
	}

	if evk.Gks != nil {
		p[n] = 1
		n++

		if inc, err = evk.Gks.Encode(p[n:]); err != nil {

			return n + inc, err
		}

		n += inc

	} else {
		n++
	}

	return
}

// Decode decodes a slice of bytes generated by Encode
// on the object and returns the number of bytes read.
func (evk *MemEvaluationKeySet) Decode(p []byte) (n int, err error) {
	var inc int
	if p[n] == 1 {
		n++

		if evk.Rlk == nil {
			evk.Rlk = new(RelinearizationKey)
		}

		if inc, err = evk.Rlk.Decode(p[n:]); err != nil {
			return n + inc, err
		}

		n += inc

	} else {
		n++
	}

	if p[n] == 1 {
		n++

		if evk.Gks == nil {
			evk.Gks = structs.Map[uint64, GaloisKey]{}
		}

		if inc, err = evk.Gks.Decode(p[n:]); err != nil {
			return n + inc, err
		}

		n += inc

	} else {
		n++
	}

	return
}
