package rlwe

import (
	"io"

	"github.com/tuneinsight/lattigo/v4/ring"
	"github.com/tuneinsight/lattigo/v4/utils/sampling"
)

// Plaintext is a common base type for RLWE plaintexts.
type Plaintext struct {
	OperandQ
	Value ring.Poly
}

// NewPlaintext creates a new Plaintext at level `level` from the parameters.
func NewPlaintext(params ParametersInterface, level int) (pt *Plaintext) {
	op := *NewOperandQ(params, 0, level)
	op.PlaintextScale = params.PlaintextScale()
	op.PlaintextLogDimensions = params.PlaintextLogDimensions()
	return &Plaintext{OperandQ: op, Value: op.Value[0]}
}

// NewPlaintextAtLevelFromPoly constructs a new Plaintext at a specific level
// where the message is set to the passed poly. No checks are performed on poly and
// the returned Plaintext will share its backing array of coefficients.
// Returned plaintext's MetaData is empty.
func NewPlaintextAtLevelFromPoly(level int, poly ring.Poly) (pt *Plaintext, err error) {
	op, err := NewOperandQAtLevelFromPoly(level, []ring.Poly{poly})
	if err != nil {
		return nil, err
	}
	return &Plaintext{OperandQ: *op, Value: op.Value[0]}, nil
}

// Copy copies the `other` plaintext value into the receiver plaintext.
func (pt Plaintext) Copy(other *Plaintext) {
	pt.OperandQ.Copy(&other.OperandQ)
	pt.Value = other.OperandQ.Value[0]
}

func (pt Plaintext) CopyNew() (ptCpy *Plaintext) {
	ptCpy = new(Plaintext)
	ptCpy.OperandQ = *pt.OperandQ.CopyNew()
	ptCpy.Value = pt.OperandQ.Value[0]
	return
}

// Equal performs a deep equal.
func (pt Plaintext) Equal(other *Plaintext) bool {
	return pt.OperandQ.Equal(&other.OperandQ) && pt.Value.Equal(&other.Value)
}

// NewPlaintextRandom generates a new uniformly distributed Plaintext.
func NewPlaintextRandom(prng sampling.PRNG, params ParametersInterface, level int) (pt *Plaintext) {
	pt = NewPlaintext(params, level)
	PopulateElementRandom(prng, params, pt.El())
	return
}

// ReadFrom reads on the object from an io.Writer. It implements the
// io.ReaderFrom interface.
//
// Unless r implements the buffer.Reader interface (see see lattigo/utils/buffer/reader.go),
// it will be wrapped into a bufio.Reader. Since this requires allocation, it
// is preferable to pass a buffer.Reader directly:
//
//   - When reading multiple values from a io.Reader, it is preferable to first
//     first wrap io.Reader in a pre-allocated bufio.Reader.
//   - When reading from a var b []byte, it is preferable to pass a buffer.NewBuffer(b)
//     as w (see lattigo/utils/buffer/buffer.go).
func (pt *Plaintext) ReadFrom(r io.Reader) (n int64, err error) {
	if n, err = pt.OperandQ.ReadFrom(r); err != nil {
		return
	}

	pt.Value = pt.OperandQ.Value[0]
	return
}

// UnmarshalBinary decodes a slice of bytes generated by MarshalBinary
// or Read on the objeop.
func (pt *Plaintext) UnmarshalBinary(p []byte) (err error) {
	if err = pt.OperandQ.UnmarshalBinary(p); err != nil {
		return
	}
	pt.Value = pt.OperandQ.Value[0]
	return
}
