package structs

import (
	"bufio"
	"fmt"
	"io"

	//"reflect"
	"encoding/binary"

	"github.com/tuneinsight/lattigo/v4/utils/buffer"
)

type Vector[T any] []*T

// BinarySize returns the size in bytes that the object once marshalled into a binary form.
func (v Vector[T]) BinarySize() (size int) {

	var err error
	var inc int

	size += 8
	for _, vi := range v {

		if inc, err = codec.BinarySizeWrapper(vi); err != nil {
			panic(err)
		}

		size += inc
	}
	return
}

// MarshalBinary encodes the object into a binary form on a newly allocated slice of bytes.
func (v *Vector[T]) MarshalBinary() (p []byte, err error) {
	p = make([]byte, v.BinarySize())
	_, err = v.Read(p)
	return
}

// Read encodes the object into a binary form on a preallocated slice of bytes
// and returns the number of bytes written.
func (v *Vector[T]) Read(b []byte) (n int, err error) {

	vi := *v

	binary.LittleEndian.PutUint64(b[n:], uint64(len(vi)))
	n += 8

	var inc int
	for i := range vi {
		if inc, err = codec.ReadWrapper(b[n:], vi[i]); err != nil {
			return n + inc, err
		}

		n += inc
	}

	return
}

// WriteTo writes the object on an io.Writer.
// To ensure optimal efficiency and minimal allocations, the user is encouraged
// to provide a struct implementing the interface buffer.Writer, which defines
// a subset of the method of the bufio.Writer.
// If w is not compliant to the buffer.Writer interface, it will be wrapped in
// a new bufio.Writer.
// For additional information, see lattigo/utils/buffer/writer.go.
func (v *Vector[T]) WriteTo(w io.Writer) (int64, error) {
	switch w := w.(type) {
	case buffer.Writer:

		var err error
		var n int64

		vi := *v

		var inc int
		if inc, err = buffer.WriteInt(w, len(vi)); err != nil {
			return int64(inc), err
		}

		n += int64(inc)

		for i := range vi {
			var inc int64
			if inc, err = codec.WriteToWrapper(w, vi[i]); err != nil {
				return n + inc, err
			}

			n += inc
		}

		return n, nil

	default:
		return v.WriteTo(bufio.NewWriter(w))
	}
}

// UnmarshalBinary decodes a slice of bytes generated by MarshalBinary,
// WriteTo or Read on the object.
func (v *Vector[T]) UnmarshalBinary(p []byte) (err error) {
	_, err = v.Write(p)
	return
}

// Write decodes a slice of bytes generated by MarshalBinary, WriteTo or
// Read on the object and returns the number of bytes read.
func (v *Vector[T]) Write(p []byte) (n int, err error) {

	size := int(binary.LittleEndian.Uint64(p[n:]))
	n += 8

	if len(*v) != size {
		*v = make([]*T, size)
	}

	vi := *v

	var inc int
	for i := range vi {

		if vi[i] == nil {
			vi[i] = new(T)
		}

		if inc, err = codec.WriteWrapper(p[n:], vi[i]); err != nil {
			return n + inc, err
		}

		n += inc
	}

	return
}

// ReadFrom reads on the object from an io.Writer.
// To ensure optimal efficiency and minimal allocations, the user is encouraged
// to provide a struct implementing the interface buffer.Reader, which defines
// a subset of the method of the bufio.Reader.
// If r is not compliant to the buffer.Reader interface, it will be wrapped in
// a new bufio.Reader.
// For additional information, see lattigo/utils/buffer/reader.go.
func (v *Vector[T]) ReadFrom(r io.Reader) (int64, error) {
	switch r := r.(type) {
	case buffer.Reader:

		var err error
		var size, n int

		if n, err = buffer.ReadInt(r, &size); err != nil {
			return int64(n), fmt.Errorf("cannot ReadFrom: size: %w", err)
		}

		if len(*v) != size {
			*v = make([]*T, size)
		}

		vi := *v

		for i := range vi {

			if vi[i] == nil {
				vi[i] = new(T)
			}

			var inc int64
			if inc, err = codec.ReadFromWrapper(r, vi[i]); err != nil {
				return int64(n) + inc, err
			}

			n += int(inc)
		}

		return int64(n), nil

	default:
		return v.ReadFrom(bufio.NewReader(r))
	}
}
