package ring

import (
	"bufio"
	"encoding/binary"
	"fmt"
	"io"

	"github.com/tuneinsight/lattigo/v4/utils/buffer"
)

// PolyVector is a struct storing a vector of *Poly.
type PolyVector []*Poly

// NewPolyVector allocates a new poly vector of the given size.
func NewPolyVector(N, Level, size int) *PolyVector {
	v := make([]*Poly, size)

	for i := range v {
		v[i] = NewPoly(N, Level)
	}

	pv := PolyVector(v)

	return &pv
}

// Set sets a poly vector to the slice of *Poly.
// Overwrites the current states of the poly vector.
func (pv *PolyVector) Set(polys []*Poly) {
	*pv = PolyVector(polys)
}

// Get returns the underlying slice of *Poly.
func (pv *PolyVector) Get() []*Poly {
	return []*Poly(*pv)
}

// N returns the ring degree of the first polynomial in the vector of polynomials.
func (pv *PolyVector) N() int {
	return (*pv)[0].N()
}

// Level returns the level of the first polynomial in the vector of polynomials.
func (pv *PolyVector) Level() int {
	return (*pv)[0].Level()
}

// Resize resizes the level and size of the vector of polynomials, allocating if necessary.
func (pv *PolyVector) Resize(level, size int) {
	N := pv.N()

	v := *pv

	for i := range v {
		v[i].Resize(level)
	}

	if len(v) > size {
		v = v[:size+1]
	} else {
		for i := len(v); i < size+1; i++ {
			v = append(v, NewPoly(N, size))
		}
	}

	*pv = v
}

// BinarySize returns the size in bytes that the object once marshalled into a binary form.
func (pv *PolyVector) BinarySize() (size int) {
	size += 8
	for _, v := range *pv {
		size += v.BinarySize()
	}
	return
}

// MarshalBinary encodes the object into a binary form on a newly allocated slice of bytes.
func (pv *PolyVector) MarshalBinary() (p []byte, err error) {
	p = make([]byte, pv.BinarySize())
	_, err = pv.Read(p)
	return
}

// Read encodes the object into a binary form on a preallocated slice of bytes
// and returns the number of bytes written.
func (pv *PolyVector) Read(b []byte) (n int, err error) {

	v := *pv

	binary.LittleEndian.PutUint64(b[n:], uint64(len(v)))
	n += 8

	var inc int
	for i := range v {
		if inc, err = v[i].Read(b[n:]); err != nil {
			return n + inc, err
		}

		n += inc
	}

	return
}

// WriteTo writes the object on an io.Writer.
// To ensure optimal efficiency and minimal allocations, the user is encouraged
// to provide a struct implementing the interface buffer.Writer, which defines
// a subset of the method of the bufio.Writer.
// If w is not compliant to the buffer.Writer interface, it will be wrapped in
// a new bufio.Writer.
// For additional information, see lattigo/utils/buffer/writer.go.
func (pv *PolyVector) WriteTo(w io.Writer) (int64, error) {
	switch w := w.(type) {
	case buffer.Writer:

		var err error
		var n int64

		v := *pv

		var inc int
		if inc, err = buffer.WriteInt(w, len(v)); err != nil {
			return int64(inc), err
		}

		n += int64(inc)

		for i := range v {
			var inc int64
			if inc, err = v[i].WriteTo(w); err != nil {
				return n + inc, err
			}

			n += inc
		}

		return n, nil

	default:
		return pv.WriteTo(bufio.NewWriter(w))
	}
}

// UnmarshalBinary decodes a slice of bytes generated by MarshalBinary
// or Read on the object.
func (pv *PolyVector) UnmarshalBinary(p []byte) (err error) {
	_, err = pv.Write(p)
	return
}

// Write decodes a slice of bytes generated by MarshalBinary, WriteTo or
// Read on the object and returns the number of bytes read.
func (pv *PolyVector) Write(p []byte) (n int, err error) {
	size := int(binary.LittleEndian.Uint64(p[n:]))
	n += 8

	if len(*pv) != size {
		*pv = make([]*Poly, size)
	}

	v := *pv

	var inc int
	for i := range v {
		if v[i] == nil {
			v[i] = new(Poly)
		}

		if inc, err = v[i].Write(p[n:]); err != nil {
			return n + inc, err
		}

		n += inc
	}

	return
}

// ReadFrom reads on the object from an io.Writer.
// To ensure optimal efficiency and minimal allocations, the user is encouraged
// to provide a struct implementing the interface buffer.Reader, which defines
// a subset of the method of the bufio.Reader.
// If r is not compliant to the buffer.Reader interface, it will be wrapped in
// a new bufio.Reader.
// For additional information, see lattigo/utils/buffer/reader.go.
func (pv *PolyVector) ReadFrom(r io.Reader) (int64, error) {
	switch r := r.(type) {
	case buffer.Reader:

		var err error
		var size, n int

		if n, err = buffer.ReadInt(r, &size); err != nil {
			return int64(n), fmt.Errorf("cannot ReadFrom: size: %w", err)
		}

		if len(*pv) != size {
			*pv = make([]*Poly, size)
		}

		v := *pv

		for i := range v {

			if v[i] == nil {
				v[i] = new(Poly)
			}

			var inc int64
			if inc, err = v[i].ReadFrom(r); err != nil {
				return int64(n) + inc, err
			}

			n += int(inc)
		}

		return int64(n), nil

	default:
		return pv.ReadFrom(bufio.NewReader(r))
	}
}
